title: PortFolio
author: 심아진
description: 심아진's PortFolio

highlighter: null
permalink: /:title

url: https://mazxyni.github.io/
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
